name: BuildPlugin
on:
    push:
        branches:
            - master

jobs:
    build:
        uses: FriendsOfShopware/workflows/.github/workflows/github.yml@main
        with:
            extensionName: RuneLaenenTwoFactorAuth
        secrets:
            ghToken: ${{ secrets.GITHUB_TOKEN }}
